version: "3.8"
services:
  api-server:
    build: .
    ports:
      - "3000:3000"
    command: ["node", "src/api-server/api-server.js"]

  raft-node1:
    build: .
    command: ["node", "src/raft-store/raft-store.js"]
    environment:
      - NODE_ID=node1

  scheduler:
    build: .
    command: ["node", "src/scheduler/scheduler.js"]

  controller:
    build: .
    command: ["node", "src/controller-manager/controller-manager.js"]

  worker:
    build: .
    command: ["node", "src/worker/worker.js"]

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
